language: php

php:
  - 5.6
  
cache:
  directories:
    - vendor

services:
  - mysql

install:
  - composer install --no-interaction
  - mysql -u root -e "CREATE DATABASE annuaire_test";


script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --stop-on-failure

addons:
    apt:
        packages:
            - sshpass
after_success:
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST 'git --git-dir=$DEPLOY_PATH/.git reset --hard HEAD'
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST 'git --git-dir=$DEPLOY_PATH/.git pull'
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST '$DEPLOY_PATH/vendor/bin/composer install'
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST 'php $DEPLOY_PATH/artisan migrate'
