language: php

php:
  - 5.6
  
cache:
  directories:
    - vendor

services:
  - mysql

install:
  - composer install --no-interaction
  - mysql -u root -e "CREATE DATABASE annuaire_test";


script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --stop-on-failure

addons:
    apt:
        packages:
            - sshpass
    ssh_known_hosts: artemis.am


after_success:
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && ls -la"
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git fetch"
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git reset --hard HEAD"
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git status"
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git pull"
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader"
