language: php

php:
  - 5.6
  
cache:
  directories:
    - vendor

services:
  - mysql

env:
  - APP_URL=http://api.annuaire.artemis.am APP_DEBUG=true API_DEBUG=true

install:
  - composer install --no-interaction
  - mysql -u root -e "CREATE DATABASE annuaire_test";


script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

addons:
    apt:
        packages:
            - sshpass
    ssh_known_hosts: artemis.am


after_success:
  - sshpass -e ssh $SSHUSER@$SSHHOST "cd $APP_PATH && tar -cf ../backup.tar ."
  - sshpass -e ssh $SSHUSER@$SSHHOST "cd $APP_PATH && git reset --hard HEAD"
  - sshpass -e ssh $SSHUSER@$SSHHOST "cd $APP_PATH && git pull"
  - sshpass -e ssh $SSHUSER@$SSHHOST "cd $APP_PATH && composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader"
  - curl --data "token=$ADMIN_TOKEN" $APP_URL/migrate
